import { addCompany, getCompanies } from "./company-storage"

// Function to initialize dummy company data
export const initializeDummyCompanies = (force = false) => {
  // Only initialize if there are no companies or force is true
  if (getCompanies().length === 0 || force) {
    // Clear existing companies if force is true
    if (force) {
      localStorage.removeItem("companies")
    }

    // Add dummy companies
    const dummyCompanies = [
      // Company 1: Global Tech Solutions
      {
        id: 1,
        name: "Global Tech Solutions Sdn Bhd",
        code: "GTS-2024",
        status: "Active",
        registrationNo: "RC202400123",
        gstSstRegNo: "GST000123456789",
        tinNo: "TIN987654321",
        companyType: "Independent",
        parentCompany: "",
        hierarchyLevel: "1",
        subsidiaries: 0,
        joiningDate: "2024-01-15",
        contractStart: "2024-01-15",
        contractEnd: "2026-01-14",
        programType: "Fully-insured",
        industry: "Technology",
        subIndustry: "Software Development",
        website: "https://globaltechsolutions.com.my",
        phoneNo: "+603-2123-4567",
        contacts: [
          {
            id: 1,
            name: "Ahmad Rahman",
            position: "Chief Executive Officer",
            email: "ahmad.rahman@globaltechsolutions.com.my",
            phone: "+6012-345-6789",
          },
          {
            id: 2,
            name: "Siti Nurhaliza",
            position: "Human Resources Director",
            email: "siti.nurhaliza@globaltechsolutions.com.my",
            phone: "+6012-345-6790",
          },
          {
            id: 3,
            name: "Lim Wei Ming",
            position: "Chief Financial Officer",
            email: "lim.weiming@globaltechsolutions.com.my",
            phone: "+6012-345-6791",
          },
        ],
        operationalSegmentation: {
          0: {
            id: 1,
            name: "Headquarters",
            code: "HQ-001",
            type: "Main Office",
            status: "Active",
            parentStructure: "",
            address: "Level 15, Menara Axiata, No. 9, Jalan Stesen Sentral 5",
            postcode: "50470",
            city: "Kuala Lumpur",
            state: "Kuala Lumpur",
            country: "Malaysia",
            remarks: "Main headquarters and primary operations center",
          },
          1: {
            id: 2,
            name: "Penang Branch",
            code: "PNG-002",
            type: "Branch Office",
            status: "Active",
            parentStructure: "HQ-001",
            address: "Unit 10-3A, Menara KOMTAR, Jalan Penang",
            postcode: "10000",
            city: "George Town",
            state: "Penang",
            country: "Malaysia",
            remarks: "Northern region operations and development center",
          },
        },
        jobGrade: {
          0: {
            category: "Executive Level",
            grades: ["Executive", "Senior Executive", "Principal Executive"],
          },
          1: {
            category: "Management Level",
            grades: ["Assistant Manager", "Manager", "Senior Manager"],
          },
          2: {
            category: "Leadership Level",
            grades: ["Director", "Senior Director", "Vice President"],
          },
        },
        reportFrequency: {
          0: {
            id: "RPT-001",
            reportType: "Claims Summary",
            reportFrequency: "Monthly",
            deliveryMethod: "Email",
            recipients: "ahmad.rahman@globaltechsolutions.com.my, siti.nurhaliza@globaltechsolutions.com.my",
          },
          1: {
            id: "RPT-002",
            reportType: "Utilization Report",
            reportFrequency: "Quarterly",
            deliveryMethod: "Portal Download",
            recipients: "lim.weiming@globaltechsolutions.com.my",
          },
          2: {
            id: "RPT-003",
            reportType: "Annual Summary",
            reportFrequency: "Annually",
            deliveryMethod: "Email & Portal",
            recipients: "ahmad.rahman@globaltechsolutions.com.my",
          },
        },
        medicalProvider: {
          providers: [
            "KPJ Healthcare Berhad",
            "Pantai Holdings Berhad",
            "Gleneagles Hospital",
            "Prince Court Medical Centre",
            "Sunway Medical Centre",
          ],
        },
        sob: {
          benefits: [
            "Outpatient: RM 5,000 per year",
            "Inpatient: RM 200,000 per year",
            "Dental: RM 2,500 per year",
            "Optical: RM 1,000 per year",
            "Maternity: RM 15,000 per pregnancy",
            "Health Screening: RM 800 per year",
            "Specialist Consultation: RM 150 per visit",
          ],
        },
        contractHistory: [
          {
            id: 1,
            startDate: "2024-01-15",
            endDate: "2026-01-14",
            status: "Active",
            modifiedBy: "System Administrator",
            modifiedDate: "2024-01-10",
          },
        ],
      },

      // Company 2: Eco Green Manufacturing
      {
        id: 2,
        name: "Eco Green Manufacturing Bhd",
        code: "EGM-2024",
        status: "Active",
        registrationNo: "RC202400456",
        gstSstRegNo: "GST000456789012",
        tinNo: "TIN876543210",
        companyType: "Independent",
        parentCompany: "",
        hierarchyLevel: "1",
        subsidiaries: 2,
        joiningDate: "2024-02-10",
        contractStart: "2024-02-15",
        contractEnd: "2027-02-14",
        programType: "Self-funded",
        industry: "Manufacturing",
        subIndustry: "Sustainable Products",
        website: "https://ecogreenmanufacturing.com.my",
        phoneNo: "+603-3456-7890",
        contacts: [
          {
            id: 1,
            name: "Tan Mei Ling",
            position: "Managing Director",
            email: "meiling.tan@ecogreenmanufacturing.com.my",
            phone: "+6012-987-6543",
          },
          {
            id: 2,
            name: "Rajesh Kumar",
            position: "HR Manager",
            email: "rajesh.kumar@ecogreenmanufacturing.com.my",
            phone: "+6012-876-5432",
          },
        ],
        operationalSegmentation: {
          0: {
            id: 1,
            name: "Main Factory",
            code: "MF-001",
            type: "Manufacturing Plant",
            status: "Active",
            parentStructure: "",
            address: "Lot 123, Jalan Perindustrian 5, Kawasan Perindustrian Shah Alam",
            postcode: "40000",
            city: "Shah Alam",
            state: "Selangor",
            country: "Malaysia",
            remarks: "Main manufacturing facility",
          },
          1: {
            id: 2,
            name: "Corporate Office",
            code: "CO-002",
            type: "Office",
            status: "Active",
            parentStructure: "MF-001",
            address: "Level 8, Menara Eco, Jalan Damansara",
            postcode: "50490",
            city: "Kuala Lumpur",
            state: "Kuala Lumpur",
            country: "Malaysia",
            remarks: "Corporate headquarters",
          },
        },
        jobGrade: {
          0: {
            category: "Factory Workers",
            grades: ["Operator", "Senior Operator", "Supervisor"],
          },
          1: {
            category: "Office Staff",
            grades: ["Executive", "Senior Executive", "Manager"],
          },
          2: {
            category: "Management",
            grades: ["Senior Manager", "Director", "C-Level"],
          },
        },
        reportFrequency: {
          0: {
            id: "RPT-001",
            reportType: "Claims Summary",
            reportFrequency: "Monthly",
            deliveryMethod: "Email",
            recipients: "meiling.tan@ecogreenmanufacturing.com.my",
          },
          1: {
            id: "RPT-002",
            reportType: "Utilization Report",
            reportFrequency: "Quarterly",
            deliveryMethod: "Portal Download",
            recipients: "rajesh.kumar@ecogreenmanufacturing.com.my",
          },
        },
        medicalProvider: {
          providers: [
            "Columbia Asia Hospital",
            "KPJ Healthcare Berhad",
            "Pantai Holdings Berhad",
            "BP Healthcare Group",
          ],
        },
        sob: {
          benefits: [
            "Outpatient: RM 3,000 per year",
            "Inpatient: RM 150,000 per year",
            "Dental: RM 1,500 per year",
            "Optical: RM 800 per year",
            "Health Screening: RM 500 per year",
          ],
        },
        contractHistory: [
          {
            id: 1,
            startDate: "2024-02-15",
            endDate: "2027-02-14",
            status: "Active",
            modifiedBy: "System Administrator",
            modifiedDate: "2024-02-05",
          },
        ],
      },

      // Company 3: Sunrise Financial Services
      {
        id: 3,
        name: "Sunrise Financial Services Sdn Bhd",
        code: "SFS-2024",
        status: "Active",
        registrationNo: "RC202400789",
        gstSstRegNo: "GST000789012345",
        tinNo: "TIN765432109",
        companyType: "Subsidiary",
        parentCompany: "Sunrise Holdings Bhd",
        hierarchyLevel: "2",
        subsidiaries: 0,
        joiningDate: "2024-03-01",
        contractStart: "2024-03-15",
        contractEnd: "2026-03-14",
        programType: "Fully-insured",
        industry: "Financial Services",
        subIndustry: "Investment Advisory",
        website: "https://sunrisefinancial.com.my",
        phoneNo: "+603-4567-8901",
        contacts: [
          {
            id: 1,
            name: "David Wong",
            position: "Chief Executive Officer",
            email: "david.wong@sunrisefinancial.com.my",
            phone: "+6012-345-7890",
          },
          {
            id: 2,
            name: "Sarah Abdullah",
            position: "Head of Human Resources",
            email: "sarah.abdullah@sunrisefinancial.com.my",
            phone: "+6012-456-7890",
          },
          {
            id: 3,
            name: "Michael Tan",
            position: "Chief Operations Officer",
            email: "michael.tan@sunrisefinancial.com.my",
            phone: "+6012-567-8901",
          },
        ],
        operationalSegmentation: {
          0: {
            id: 1,
            name: "Headquarters",
            code: "HQ-001",
            type: "Main Office",
            status: "Active",
            parentStructure: "",
            address: "Level 20, Menara Sunrise, Jalan Sultan Ismail",
            postcode: "50250",
            city: "Kuala Lumpur",
            state: "Kuala Lumpur",
            country: "Malaysia",
            remarks: "Main headquarters",
          },
          1: {
            id: 2,
            name: "Johor Branch",
            code: "JB-002",
            type: "Branch Office",
            status: "Active",
            parentStructure: "HQ-001",
            address: "Unit 5-1, Menara JB, Jalan Wong Ah Fook",
            postcode: "80000",
            city: "Johor Bahru",
            state: "Johor",
            country: "Malaysia",
            remarks: "Southern region branch",
          },
        },
        jobGrade: {
          0: {
            category: "Associates",
            grades: ["Associate", "Senior Associate", "Principal Associate"],
          },
          1: {
            category: "Management",
            grades: ["Assistant Manager", "Manager", "Senior Manager"],
          },
          2: {
            category: "Executive",
            grades: ["Director", "Executive Director", "C-Suite"],
          },
        },
        reportFrequency: {
          0: {
            id: "RPT-001",
            reportType: "Claims Summary",
            reportFrequency: "Monthly",
            deliveryMethod: "Email",
            recipients: "sarah.abdullah@sunrisefinancial.com.my",
          },
          1: {
            id: "RPT-002",
            reportType: "Utilization Report",
            reportFrequency: "Quarterly",
            deliveryMethod: "Portal Download",
            recipients: "michael.tan@sunrisefinancial.com.my",
          },
          2: {
            id: "RPT-003",
            reportType: "Annual Summary",
            reportFrequency: "Annually",
            deliveryMethod: "Email & Portal",
            recipients: "david.wong@sunrisefinancial.com.my",
          },
        },
        medicalProvider: {
          providers: [
            "Gleneagles Hospital",
            "Prince Court Medical Centre",
            "Thomson Hospital Kota Damansara",
            "Pantai Hospital Kuala Lumpur",
            "Subang Jaya Medical Centre",
          ],
        },
        sob: {
          benefits: [
            "Outpatient: RM 8,000 per year",
            "Inpatient: RM 250,000 per year",
            "Dental: RM 3,000 per year",
            "Optical: RM 1,500 per year",
            "Maternity: RM 20,000 per pregnancy",
            "Health Screening: RM 1,200 per year",
            "Specialist Consultation: RM 200 per visit",
            "Mental Health: RM 5,000 per year",
          ],
        },
        contractHistory: [
          {
            id: 1,
            startDate: "2024-03-15",
            endDate: "2026-03-14",
            status: "Active",
            modifiedBy: "System Administrator",
            modifiedDate: "2024-03-01",
          },
        ],
      },

      // Company 4: Harmony Healthcare Group
      {
        id: 4,
        name: "Harmony Healthcare Group Bhd",
        code: "HHG-2024",
        status: "Inactive",
        registrationNo: "RC202401012",
        gstSstRegNo: "GST001012345678",
        tinNo: "TIN654321098",
        companyType: "Independent",
        parentCompany: "",
        hierarchyLevel: "1",
        subsidiaries: 3,
        joiningDate: "2024-01-05",
        contractStart: "2024-01-10",
        contractEnd: "2024-04-09",
        programType: "Fully-insured",
        industry: "Healthcare",
        subIndustry: "Medical Services",
        website: "https://harmonyhealthcare.com.my",
        phoneNo: "+603-5678-9012",
        contacts: [
          {
            id: 1,
            name: "Dr. Aisha Lim",
            position: "Chief Executive Officer",
            email: "aisha.lim@harmonyhealthcare.com.my",
            phone: "+6012-678-9012",
          },
          {
            id: 2,
            name: "Jason Lee",
            position: "HR Director",
            email: "jason.lee@harmonyhealthcare.com.my",
            phone: "+6012-789-0123",
          },
        ],
        operationalSegmentation: {
          0: {
            id: 1,
            name: "Main Hospital",
            code: "MH-001",
            type: "Hospital",
            status: "Active",
            parentStructure: "",
            address: "123, Jalan Medic, Taman Harmony",
            postcode: "56000",
            city: "Kuala Lumpur",
            state: "Kuala Lumpur",
            country: "Malaysia",
            remarks: "Main hospital facility",
          },
          1: {
            id: 2,
            name: "Clinic Network - Central",
            code: "CN-002",
            type: "Clinic Network",
            status: "Active",
            parentStructure: "MH-001",
            address: "45, Jalan Kesihatan, Taman Sejahtera",
            postcode: "47500",
            city: "Petaling Jaya",
            state: "Selangor",
            country: "Malaysia",
            remarks: "Central region clinic network",
          },
        },
        jobGrade: {
          0: {
            category: "Medical Staff",
            grades: ["Junior Doctor", "Doctor", "Senior Doctor", "Specialist"],
          },
          1: {
            category: "Nursing Staff",
            grades: ["Nurse", "Senior Nurse", "Head Nurse"],
          },
          2: {
            category: "Administrative",
            grades: ["Executive", "Manager", "Director"],
          },
        },
        reportFrequency: {
          0: {
            id: "RPT-001",
            reportType: "Claims Summary",
            reportFrequency: "Monthly",
            deliveryMethod: "Email",
            recipients: "jason.lee@harmonyhealthcare.com.my",
          },
        },
        medicalProvider: {
          providers: ["Self-provided", "Panel of Specialists"],
        },
        sob: {
          benefits: [
            "Outpatient: RM 10,000 per year",
            "Inpatient: RM 300,000 per year",
            "Dental: RM 5,000 per year",
            "Optical: RM 2,000 per year",
            "Maternity: RM 25,000 per pregnancy",
            "Health Screening: RM 2,000 per year",
            "Specialist Consultation: Full coverage",
          ],
        },
        contractHistory: [
          {
            id: 1,
            startDate: "2024-01-10",
            endDate: "2024-04-09",
            status: "Expired",
            modifiedBy: "System Administrator",
            modifiedDate: "2024-01-05",
          },
        ],
      },

      // Company 5: Oceanic Logistics International
      {
        id: 5,
        name: "Oceanic Logistics International Sdn Bhd",
        code: "OLI-2024",
        status: "Active",
        registrationNo: "RC202401345",
        gstSstRegNo: "GST001345678901",
        tinNo: "TIN543210987",
        companyType: "Independent",
        parentCompany: "",
        hierarchyLevel: "1",
        subsidiaries: 1,
        joiningDate: "2024-04-01",
        contractStart: "2024-04-15",
        contractEnd: "2027-04-14",
        programType: "Self-funded",
        industry: "Logistics",
        subIndustry: "International Shipping",
        website: "https://oceaniclogistics.com.my",
        phoneNo: "+603-6789-0123",
        contacts: [
          {
            id: 1,
            name: "Captain Ismail Abdullah",
            position: "Managing Director",
            email: "ismail.abdullah@oceaniclogistics.com.my",
            phone: "+6012-890-1234",
          },
          {
            id: 2,
            name: "Priya Sharma",
            position: "HR & Admin Manager",
            email: "priya.sharma@oceaniclogistics.com.my",
            phone: "+6012-901-2345",
          },
          {
            id: 3,
            name: "Chong Wei Liang",
            position: "Operations Director",
            email: "weiliang.chong@oceaniclogistics.com.my",
            phone: "+6012-012-3456",
          },
        ],
        operationalSegmentation: {
          0: {
            id: 1,
            name: "Port Klang Hub",
            code: "PKH-001",
            type: "Logistics Hub",
            status: "Active",
            parentStructure: "",
            address: "Lot 789, North Port, Port Klang",
            postcode: "42000",
            city: "Port Klang",
            state: "Selangor",
            country: "Malaysia",
            remarks: "Main logistics hub",
          },
          1: {
            id: 2,
            name: "Corporate Office",
            code: "CO-002",
            type: "Office",
            status: "Active",
            parentStructure: "PKH-001",
            address: "Level 12, Menara Ocean, Jalan Ampang",
            postcode: "50450",
            city: "Kuala Lumpur",
            state: "Kuala Lumpur",
            country: "Malaysia",
            remarks: "Corporate headquarters",
          },
          2: {
            id: 3,
            name: "Penang Operations",
            code: "PO-003",
            type: "Branch Office",
            status: "Active",
            parentStructure: "PKH-001",
            address: "Unit 5, Butterworth Logistics Center, Jalan Chain Ferry",
            postcode: "12100",
            city: "Butterworth",
            state: "Penang",
            country: "Malaysia",
            remarks: "Northern operations center",
          },
        },
        jobGrade: {
          0: {
            category: "Port Operations",
            grades: ["Port Worker", "Supervisor", "Manager"],
          },
          1: {
            category: "Logistics Staff",
            grades: ["Coordinator", "Executive", "Senior Executive"],
          },
          2: {
            category: "Management",
            grades: ["Manager", "Senior Manager", "Director"],
          },
          3: {
            category: "Maritime Staff",
            grades: ["Crew Member", "Officer", "Captain"],
          },
        },
        reportFrequency: {
          0: {
            id: "RPT-001",
            reportType: "Claims Summary",
            reportFrequency: "Monthly",
            deliveryMethod: "Email",
            recipients: "priya.sharma@oceaniclogistics.com.my",
          },
          1: {
            id: "RPT-002",
            reportType: "Utilization Report",
            reportFrequency: "Quarterly",
            deliveryMethod: "Portal Download",
            recipients: "weiliang.chong@oceaniclogistics.com.my",
          },
          2: {
            id: "RPT-003",
            reportType: "Annual Summary",
            reportFrequency: "Annually",
            deliveryMethod: "Email & Portal",
            recipients: "ismail.abdullah@oceaniclogistics.com.my",
          },
        },
        medicalProvider: {
          providers: [
            "KPJ Healthcare Berhad",
            "Columbia Asia Hospital",
            "Pantai Holdings Berhad",
            "BP Healthcare Group",
            "Klinik Kesihatan Port Klang",
          ],
        },
        sob: {
          benefits: [
            "Outpatient: RM 4,000 per year",
            "Inpatient: RM 180,000 per year",
            "Dental: RM 2,000 per year",
            "Optical: RM 1,200 per year",
            "Health Screening: RM 1,000 per year",
            "Specialist Consultation: RM 180 per visit",
            "Emergency Medical Evacuation: Covered worldwide",
          ],
        },
        contractHistory: [
          {
            id: 1,
            startDate: "2024-04-15",
            endDate: "2027-04-14",
            status: "Active",
            modifiedBy: "System Administrator",
            modifiedDate: "2024-04-01",
          },
        ],
      },
      // Company 6: PMCare Sdn Bhd
      {
        id: 6,
        name: "PMCare Sdn Bhd",
        code: "PMC-2024",
        status: "Active",
        registrationNo: "RC202401678",
        gstSstRegNo: "GST001678901234",
        tinNo: "TIN432109876",
        companyType: "Independent",
        parentCompany: "",
        hierarchyLevel: "1",
        subsidiaries: 0,
        joiningDate: "2024-05-15",
        contractStart: "2024-06-01",
        contractEnd: "2027-05-31",
        programType: "Third-Party Administrator",
        industry: "Healthcare",
        subIndustry: "Healthcare Technology",
        website: "https://pmcare.com.my",
        phoneNo: "+603-7890-1234",
        contacts: [
          {
            id: 1,
            name: "Dato' Ahmad Zaki Ismail",
            position: "Chief Executive Officer",
            email: "ahmad.zaki@pmcare.com.my",
            phone: "+6012-345-6789",
          },
          {
            id: 2,
            name: "Dr. Sarah Lim Wei Ming",
            position: "Chief Medical Officer",
            email: "sarah.lim@pmcare.com.my",
            phone: "+6012-456-7890",
          },
          {
            id: 3,
            name: "Mohd Hafiz Rahman",
            position: "Head of Operations",
            email: "hafiz.rahman@pmcare.com.my",
            phone: "+6012-567-8901",
          },
        ],
        operationalSegmentation: {
          0: {
            id: 1,
            name: "Headquarters",
            code: "HQ-001",
            type: "Main Office",
            status: "Active",
            parentStructure: "",
            address: "Level 15, Menara PMCare, No. 8, Jalan Kiara, Mont Kiara",
            postcode: "50480",
            city: "Kuala Lumpur",
            state: "Kuala Lumpur",
            country: "Malaysia",
            remarks: "Main headquarters and operations center",
          },
          1: {
            id: 2,
            name: "Technology Hub",
            code: "TH-002",
            type: "Office",
            status: "Active",
            parentStructure: "HQ-001",
            address: "Block D, Cyberjaya Tech Park, Persiaran Multimedia",
            postcode: "63000",
            city: "Cyberjaya",
            state: "Selangor",
            country: "Malaysia",
            remarks: "Technology development and innovation center",
          },
        },
        jobGrade: {
          0: {
            category: "Technical Staff",
            grades: ["Junior Developer", "Developer", "Senior Developer", "Lead Developer"],
          },
          1: {
            category: "Medical Staff",
            grades: ["Medical Officer", "Senior Medical Officer", "Medical Advisor"],
          },
          2: {
            category: "Management",
            grades: ["Manager", "Senior Manager", "Director", "C-Level"],
          },
        },
        reportFrequency: {
          0: {
            id: "RPT-001",
            reportType: "Claims Processing Summary",
            reportFrequency: "Weekly",
            deliveryMethod: "Email",
            recipients: "hafiz.rahman@pmcare.com.my",
          },
          1: {
            id: "RPT-002",
            reportType: "Client Utilization Report",
            reportFrequency: "Monthly",
            deliveryMethod: "Portal Download",
            recipients: "sarah.lim@pmcare.com.my",
          },
          2: {
            id: "RPT-003",
            reportType: "Executive Dashboard",
            reportFrequency: "Monthly",
            deliveryMethod: "Email & Portal",
            recipients: "ahmad.zaki@pmcare.com.my",
          },
        },
        medicalProvider: {
          providers: [
            "All major hospitals and clinics in Malaysia",
            "KPJ Healthcare Network",
            "Pantai Hospital Group",
            "Columbia Asia Hospitals",
            "Gleneagles Hospitals",
            "PMCare Panel Clinics Network (650+ clinics)",
          ],
        },
        sob: {
          benefits: [
            "Claims Processing Services",
            "Healthcare Provider Network Management",
            "Medical Case Management",
            "Utilization Review",
            "Healthcare Analytics",
            "Mobile App for Members",
            "24/7 Medical Helpline",
            "Telehealth Services",
          ],
        },
        contractHistory: [
          {
            id: 1,
            startDate: "2024-06-01",
            endDate: "2027-05-31",
            status: "Active",
            modifiedBy: "System Administrator",
            modifiedDate: "2024-05-20",
          },
        ],
      },
    ]

    // Add each dummy company to storage
    dummyCompanies.forEach((company) => {
      addCompany(company)
    })

    console.log("Complete dummy company data initialized successfully")
    return true
  }

  console.log("Dummy companies already exist, skipping initialization")
  return false
}
