import { PayorStorage } from "./payor-storage"
import type { Payor } from "./payor-storage"

// Function to initialize dummy payor data
export const initializeDummyPayors = (force = false) => {
  // Only initialize if there are no payors or force is true
  if (PayorStorage.getAllPayors().length === 0 || force) {
    // Clear existing payors if force is true
    if (force) {
      PayorStorage.clearAllData()
    }

    // Add 5 complete dummy payors
    const dummyPayors: Payor[] = [
      {
        id: "PAY-001",
        name: "Great Eastern Life Assurance (Malaysia) Berhad",
        code: "GELAM",
        address: "Menara Great Eastern, 303 Jalan Ampang",
        city: "Kuala Lumpur",
        postcode: "50450",
        state: "Kuala Lumpur",
        country: "Malaysia",
        remarks: "Leading life insurance company in Malaysia with comprehensive medical coverage",
        status: "Active",
        contacts: [
          {
            id: "CON-001-001",
            name: "Dato' Koh Yaw Hui",
            category: "Management",
            designation: "Chief Executive Officer",
            email: "koh.yawhui@greateastern.com.my",
            mobileNo: "+6012-234-5678",
            officeNo: "+603-4259-8888",
            extNo: "1001",
            status: "Active",
            remarks: "Primary contact for strategic partnerships",
          },
          {
            id: "CON-001-002",
            name: "Lim Bee Choo",
            category: "Operations",
            designation: "Head of Group Medical",
            email: "lim.beechoo@greateastern.com.my",
            mobileNo: "+6012-345-6789",
            officeNo: "+603-4259-8888",
            extNo: "2001",
            status: "Active",
            remarks: "Medical claims and operations specialist",
          },
          {
            id: "CON-001-003",
            name: "Ahmad Faizal Rahman",
            category: "Customer Service",
            designation: "Customer Relations Manager",
            email: "ahmad.faizal@greateastern.com.my",
            mobileNo: "+6012-456-7890",
            officeNo: "+603-4259-8888",
            extNo: "3001",
            status: "Active",
            remarks: "Customer service and support coordination",
          },
        ],
      },
      {
        id: "PAY-002",
        name: "Allianz Malaysia Berhad",
        code: "ALLMB",
        address: "Level 29, Menara Allianz Sentral, 203 Jalan Tun Sambanthan",
        city: "Kuala Lumpur",
        postcode: "50470",
        state: "Kuala Lumpur",
        country: "Malaysia",
        remarks: "International insurance provider with strong presence in Malaysia",
        status: "Active",
        contacts: [
          {
            id: "CON-002-001",
            name: "Sean Wang",
            category: "Management",
            designation: "Chief Executive Officer",
            email: "sean.wang@allianz.com.my",
            mobileNo: "+6012-567-8901",
            officeNo: "+603-2264-1188",
            extNo: "1001",
            status: "Active",
            remarks: "Executive leadership and strategic direction",
          },
          {
            id: "CON-002-002",
            name: "Siti Aishah Mohd Noor",
            category: "Operations",
            designation: "Head of Health Insurance",
            email: "siti.aishah@allianz.com.my",
            mobileNo: "+6012-678-9012",
            officeNo: "+603-2264-1188",
            extNo: "2002",
            status: "Active",
            remarks: "Health insurance products and claims management",
          },
        ],
      },
      {
        id: "PAY-003",
        name: "AIA Bhd.",
        code: "AIABHD",
        address: "Level 18, Menara AIA Sentral, 30 Jalan Sultan Ismail",
        city: "Kuala Lumpur",
        postcode: "50250",
        state: "Kuala Lumpur",
        country: "Malaysia",
        remarks: "Pan-Asian life insurance group with comprehensive medical benefits",
        status: "Active",
        contacts: [
          {
            id: "CON-003-001",
            name: "Goh Thean Eu",
            category: "Management",
            designation: "Chief Executive Officer",
            email: "goh.theaneu@aia.com.my",
            mobileNo: "+6012-789-0123",
            officeNo: "+603-2056-1111",
            extNo: "1001",
            status: "Active",
            remarks: "Strategic leadership and business development",
          },
          {
            id: "CON-003-002",
            name: "Dr. Lim Swee Cheng",
            category: "Medical",
            designation: "Chief Medical Officer",
            email: "dr.lim@aia.com.my",
            mobileNo: "+6012-890-1234",
            officeNo: "+603-2056-1111",
            extNo: "2003",
            status: "Active",
            remarks: "Medical underwriting and clinical governance",
          },
          {
            id: "CON-003-003",
            name: "Nurul Huda Kassim",
            category: "Operations",
            designation: "Head of Group Business",
            email: "nurul.huda@aia.com.my",
            mobileNo: "+6012-901-2345",
            officeNo: "+603-2056-1111",
            extNo: "3003",
            status: "Active",
            remarks: "Corporate client relationship management",
          },
        ],
      },
      {
        id: "PAY-004",
        name: "Prudential Assurance Malaysia Berhad",
        code: "PAMB",
        address: "Level 7, Setia Walk, No. 2, Jalan Setia Dagang AH U13/AH",
        city: "Shah Alam",
        postcode: "40170",
        state: "Selangor",
        country: "Malaysia",
        remarks: "Leading life insurer providing innovative insurance and investment solutions",
        status: "Active",
        contacts: [
          {
            id: "CON-004-001",
            name: "Lilian Ng",
            category: "Management",
            designation: "Chief Executive Officer",
            email: "lilian.ng@prudential.com.my",
            mobileNo: "+6013-012-3456",
            officeNo: "+603-2053-8888",
            extNo: "1001",
            status: "Active",
            remarks: "Executive management and strategic planning",
          },
          {
            id: "CON-004-002",
            name: "Mohd Rizal Abdullah",
            category: "Operations",
            designation: "Head of Employee Benefits",
            email: "mohd.rizal@prudential.com.my",
            mobileNo: "+6013-123-4567",
            officeNo: "+603-2053-8888",
            extNo: "2004",
            status: "Active",
            remarks: "Employee benefits and group insurance specialist",
          },
        ],
      },
      {
        id: "PAY-005",
        name: "Zurich General Insurance Malaysia Berhad",
        code: "ZGIMB",
        address: "Level 23A, Menara Milenium, Jalan Damanlela",
        city: "Petaling Jaya",
        postcode: "47820",
        state: "Selangor",
        country: "Malaysia",
        remarks: "Global insurance company providing comprehensive risk protection solutions",
        status: "Active",
        contacts: [
          {
            id: "CON-005-001",
            name: "Antony Lee",
            category: "Management",
            designation: "Chief Executive Officer",
            email: "antony.lee@zurich.com.my",
            mobileNo: "+6013-234-5678",
            officeNo: "+603-2332-6000",
            extNo: "1001",
            status: "Active",
            remarks: "Corporate leadership and business strategy",
          },
          {
            id: "CON-005-002",
            name: "Tan Mei Ling",
            category: "Operations",
            designation: "Head of Corporate Solutions",
            email: "tan.meiling@zurich.com.my",
            mobileNo: "+6013-345-6789",
            officeNo: "+603-2332-6000",
            extNo: "2005",
            status: "Active",
            remarks: "Corporate insurance solutions and client management",
          },
          {
            id: "CON-005-003",
            name: "Dr. Rajesh Kumar",
            category: "Medical",
            designation: "Medical Advisor",
            email: "dr.rajesh@zurich.com.my",
            mobileNo: "+6013-456-7890",
            officeNo: "+603-2332-6000",
            extNo: "3005",
            status: "Active",
            remarks: "Medical consultation and claims assessment",
          },
        ],
      },
      {
        id: "PAY-006",
        name: "PMCare Sdn Bhd",
        code: "PMC001",
        address: "Level 15, Menara PMCare, Jalan Bukit Bintang",
        city: "Kuala Lumpur",
        postcode: "55100",
        state: "Kuala Lumpur",
        country: "Malaysia",
        remarks: "Healthcare management and third-party administrator specializing in medical benefits administration",
        status: "Active",
        contacts: [
          {
            id: "CON-006-001",
            name: "Dato' Ahmad Rashid",
            category: "Management",
            designation: "Chief Executive Officer",
            email: "ahmad.rashid@pmcare.com.my",
            mobileNo: "+6012-345-6789",
            officeNo: "+603-2148-8000",
            extNo: "1001",
            status: "Active",
            remarks: "Executive leadership and strategic direction",
          },
          {
            id: "CON-006-002",
            name: "Dr. Sarah Lim",
            category: "Medical",
            designation: "Chief Medical Officer",
            email: "dr.sarah@pmcare.com.my",
            mobileNo: "+6012-456-7890",
            officeNo: "+603-2148-8000",
            extNo: "2001",
            status: "Active",
            remarks: "Medical oversight and clinical governance",
          },
          {
            id: "CON-006-003",
            name: "Jennifer Wong",
            category: "Operations",
            designation: "Head of Operations",
            email: "jennifer.wong@pmcare.com.my",
            mobileNo: "+6012-567-8901",
            officeNo: "+603-2148-8000",
            extNo: "3001",
            status: "Active",
            remarks: "Operations management and client services",
          },
        ],
      },
    ]

    // Add each dummy payor to storage
    dummyPayors.forEach((payor) => {
      PayorStorage.addPayor(payor)
    })

    console.log("6 complete dummy payor entries initialized successfully")
    return true
  }

  console.log("Dummy payors already exist, skipping initialization")
  return false
}
