import { saveProvider, getProviders } from "./provider-storage"

export function initializeDummyProviders() {
  // Check if providers already exist
  const existingProviders = getProviders()
  if (existingProviders.length > 0) {
    return // Don't initialize if data already exists
  }

  const dummyProviders = [
    {
      providerName: "City General Hospital",
      providerCode: "CGH001",
      providerType: "Hospital",
      specialization: "General Medicine",
      contactPerson: "Dr. Sarah Johnson",
      phoneNumber: "+1-555-0101",
      email: "admin@citygeneral.com",
      address: "123 Medical Center Drive",
      city: "New York",
      state: "NY",
      postalCode: "10001",
      country: "United States",
      status: "Active" as const,
      registrationNumber: "REG-CGH-2023-001",
      licenseNumber: "LIC-NY-12345",
      accreditation: "Joint Commission",
      contractStartDate: "2023-01-01",
      contractEndDate: "2025-12-31",
      paymentTerms: "Net 30",
    },
    {
      providerName: "Metro Cardiology Clinic",
      providerCode: "MCC002",
      providerType: "Clinic",
      specialization: "Cardiology",
      contactPerson: "Dr. Michael Chen",
      phoneNumber: "+1-555-0102",
      email: "info@metrocardio.com",
      address: "456 Heart Avenue",
      city: "Los Angeles",
      state: "CA",
      postalCode: "90210",
      country: "United States",
      status: "Active" as const,
      registrationNumber: "REG-MCC-2023-002",
      licenseNumber: "LIC-CA-67890",
      accreditation: "American College of Cardiology",
      contractStartDate: "2023-03-15",
      contractEndDate: "2026-03-14",
      paymentTerms: "Net 15",
    },
    {
      providerName: "Sunshine Pediatrics",
      providerCode: "SP003",
      providerType: "Clinic",
      specialization: "Pediatrics",
      contactPerson: "Dr. Emily Rodriguez",
      phoneNumber: "+1-555-0103",
      email: "contact@sunshinepeds.com",
      address: "789 Children's Way",
      city: "Miami",
      state: "FL",
      postalCode: "33101",
      country: "United States",
      status: "Active" as const,
      registrationNumber: "REG-SP-2023-003",
      licenseNumber: "LIC-FL-11111",
      accreditation: "American Academy of Pediatrics",
      contractStartDate: "2023-02-01",
      contractEndDate: "2025-01-31",
      paymentTerms: "Net 30",
    },
    {
      providerName: "Advanced Imaging Center",
      providerCode: "AIC004",
      providerType: "Diagnostic Center",
      specialization: "Radiology",
      contactPerson: "Dr. Robert Kim",
      phoneNumber: "+1-555-0104",
      email: "scheduling@advancedimaging.com",
      address: "321 Scan Street",
      city: "Chicago",
      state: "IL",
      postalCode: "60601",
      country: "United States",
      status: "Inactive" as const,
      registrationNumber: "REG-AIC-2023-004",
      licenseNumber: "LIC-IL-22222",
      accreditation: "American College of Radiology",
      contractStartDate: "2023-01-15",
      contractEndDate: "2024-01-14",
      paymentTerms: "Net 45",
    },
    {
      providerName: "Family Wellness Pharmacy",
      providerCode: "FWP005",
      providerType: "Pharmacy",
      specialization: "Retail Pharmacy",
      contactPerson: "PharmD Lisa Wang",
      phoneNumber: "+1-555-0105",
      email: "info@familywellness.com",
      address: "654 Wellness Boulevard",
      city: "Seattle",
      state: "WA",
      postalCode: "98101",
      country: "United States",
      status: "Active" as const,
      registrationNumber: "REG-FWP-2023-005",
      licenseNumber: "LIC-WA-33333",
      accreditation: "NABP Accredited",
      contractStartDate: "2023-04-01",
      contractEndDate: "2025-03-31",
      paymentTerms: "Net 30",
    },
  ]

  // Save each dummy provider
  dummyProviders.forEach((provider) => {
    saveProvider(provider)
  })
}
