import { PlanStorage, type Plan } from "./plan-storage"

// 5 Complete Plan dummy data entries
const dummyPlans: Plan[] = [
  {
    id: "PL001",
    name: "Basic Medical Plan",
    type: "Corporate Self-Funded",
    status: "Active",
    createdDate: "2024-01-15",
    description: "Basic medical coverage plan for employees with essential health benefits",
    effectiveDate: "2024-01-01",
    expiryDate: "2024-12-31",
    serviceTypes: ["GP", "SP", "OC"],
    subServiceTypes: {
      GP: ["gp_primary_care", "gp_preventive", "gp_chronic"],
      SP: ["sp_cardiology", "sp_dermatology", "sp_endocrinology"],
      OC: ["oc_examination", "oc_vision_correction"],
    },
    providerAccess: "panel",
    selectedProviders: [
      {
        id: "prov-001",
        name: "General Medical Center",
        type: "Hospital",
        location: "Downtown",
        status: "Active",
        phone: "+1-555-0101",
        hours: "24/7",
      },
      {
        id: "prov-002",
        name: "Family Health Clinic",
        type: "Clinic",
        location: "Suburb",
        status: "Active",
        phone: "+1-555-0102",
        hours: "8AM-6PM",
      },
    ],
    hasBillback: false,
    hasSpecialRules: true,
    limits: [
      {
        id: "limit-001",
        name: "Annual Medical Limit",
        amount: 50000,
        currency: "USD",
        period: "Annual",
        limitType: "independent",
        memberRoles: ["Employee", "Spouse"],
        serviceTypes: ["GP", "SP"],
        description: "Annual limit for medical consultations",
      },
      {
        id: "limit-002",
        name: "Optical Services Limit",
        amount: 2000,
        currency: "USD",
        period: "Annual",
        limitType: "independent",
        memberRoles: ["Employee", "Spouse", "Child"],
        serviceTypes: ["OC"],
        description: "Annual limit for optical services",
      },
    ],
    specialRules: {
      coPayments: [
        {
          id: "copay-001",
          type: "Fixed Amount",
          serviceType: "GP",
          paymentMethod: "Per Visit",
          amount: 15,
          unit: "USD",
          isSequential: false,
          description: "Fixed co-payment for GP consultations",
        },
      ],
      benefitCoordination: [
        {
          id: "bc-001",
          type: "Primary",
          description: "This plan acts as primary coverage",
          priority: 1,
        },
      ],
      regulatoryCompliance: {
        essentialHealthBenefits: {
          enabled: true,
          categories: ["Ambulatory", "Emergency", "Preventive"],
          exemptions: [],
        },
        preventiveCareExemptions: {
          enabled: true,
          services: ["Annual Checkup", "Vaccinations"],
          copaymentWaived: true,
        },
        mentalHealthParity: {
          enabled: false,
          treatmentLimits: false,
          financialRequirements: false,
          quantitativeLimits: false,
        },
      },
    },
    coPayments: [
      {
        id: "copay-001",
        type: "Fixed Amount",
        serviceType: "GP",
        paymentMethod: "Per Visit",
        amount: 15,
        unit: "USD",
        isSequential: false,
        description: "Fixed co-payment for GP consultations",
      },
    ],
  },
  {
    id: "PL002",
    name: "Premium Health Plan",
    type: "GHS: Group Hospitalization & Surgery",
    status: "Active",
    createdDate: "2024-01-10",
    description: "Comprehensive health coverage with hospitalization and surgery benefits",
    effectiveDate: "2024-01-01",
    expiryDate: "2024-12-31",
    serviceTypes: ["GP", "SP", "OC", "DT", "HP", "SG"],
    subServiceTypes: {
      GP: ["gp_primary_care", "gp_preventive", "gp_chronic", "gp_wellness"],
      SP: ["sp_cardiology", "sp_dermatology", "sp_neurology", "sp_orthopedics"],
      OC: ["oc_examination", "oc_vision_correction", "oc_eye_surgery"],
      DT: ["dt_preventive", "dt_restorative", "dt_oral_surgery"],
      HP: ["hp_room_board", "hp_nursing", "hp_hospital_services"],
      SG: ["sg_minor", "sg_major", "sg_day_surgery"],
    },
    providerAccess: "select-access",
    selectedProviders: [
      {
        id: "prov-003",
        name: "City General Hospital",
        type: "Hospital",
        location: "Medical District",
        status: "Active",
        phone: "+1-555-0103",
        hours: "24/7",
      },
      {
        id: "prov-004",
        name: "Specialist Medical Center",
        type: "Clinic",
        location: "Healthcare Plaza",
        status: "Active",
        phone: "+1-555-0104",
        hours: "7AM-9PM",
      },
      {
        id: "prov-005",
        name: "Dental Care Associates",
        type: "Dental",
        location: "Dental Center",
        status: "Active",
        phone: "+1-555-0105",
        hours: "8AM-7PM",
      },
    ],
    hasBillback: true,
    hasSpecialRules: true,
    limits: [
      {
        id: "limit-003",
        name: "Annual Medical Limit",
        amount: 100000,
        currency: "USD",
        period: "Annual",
        limitType: "independent",
        memberRoles: ["Employee", "Spouse", "Child"],
        serviceTypes: ["GP", "SP", "OC", "DT"],
        description: "Annual limit for outpatient medical services",
      },
      {
        id: "limit-004",
        name: "Hospitalization Limit",
        amount: 500000,
        currency: "USD",
        period: "Annual",
        limitType: "independent",
        memberRoles: ["Employee", "Spouse", "Child"],
        serviceTypes: ["HP", "SG"],
        description: "Annual limit for hospitalization and surgery",
      },
    ],
    specialRules: {
      coPayments: [
        {
          id: "copay-002",
          type: "Fixed Amount",
          serviceType: "GP",
          paymentMethod: "Per Visit",
          amount: 20,
          unit: "USD",
          isSequential: false,
          description: "Fixed co-payment for GP consultations",
        },
        {
          id: "copay-003",
          type: "Percentage",
          serviceType: "SP",
          paymentMethod: "Per Visit",
          amount: 10,
          unit: "%",
          isSequential: false,
          description: "10% co-payment for specialist consultations",
        },
      ],
      benefitCoordination: [
        {
          id: "bc-002",
          type: "Primary",
          description: "This plan acts as primary coverage for hospitalization",
          priority: 1,
        },
      ],
      regulatoryCompliance: {
        essentialHealthBenefits: {
          enabled: true,
          categories: ["Ambulatory", "Emergency", "Hospitalization", "Surgery"],
          exemptions: [],
        },
        preventiveCareExemptions: {
          enabled: true,
          services: ["Annual Checkup", "Health Screening", "Dental Cleaning"],
          copaymentWaived: true,
        },
        mentalHealthParity: {
          enabled: true,
          treatmentLimits: false,
          financialRequirements: false,
          quantitativeLimits: false,
        },
      },
    },
    coPayments: [
      {
        id: "copay-002",
        type: "Fixed Amount",
        serviceType: "GP",
        paymentMethod: "Per Visit",
        amount: 20,
        unit: "USD",
        isSequential: false,
        description: "Fixed co-payment for GP consultations",
      },
      {
        id: "copay-003",
        type: "Percentage",
        serviceType: "SP",
        paymentMethod: "Per Visit",
        amount: 10,
        unit: "%",
        isSequential: false,
        description: "10% co-payment for specialist consultations",
      },
    ],
  },
  {
    id: "PL003",
    name: "Dental Care Plan",
    type: "Personal Insurance",
    status: "Draft",
    createdDate: "2024-01-20",
    description: "Comprehensive dental coverage plan with orthodontic benefits",
    effectiveDate: "2024-02-01",
    expiryDate: "2024-12-31",
    serviceTypes: ["DT"],
    subServiceTypes: {
      DT: ["dt_preventive", "dt_restorative", "dt_oral_surgery", "dt_orthodontics", "dt_periodontics"],
    },
    providerAccess: "panel",
    selectedProviders: [
      {
        id: "prov-006",
        name: "Smile Dental Clinic",
        type: "Dental",
        location: "Main Street",
        status: "Active",
        phone: "+1-555-0106",
        hours: "8AM-6PM",
      },
      {
        id: "prov-007",
        name: "Orthodontic Specialists",
        type: "Dental",
        location: "Dental Plaza",
        status: "Active",
        phone: "+1-555-0107",
        hours: "9AM-5PM",
      },
    ],
    hasBillback: false,
    hasSpecialRules: true,
    limits: [
      {
        id: "limit-005",
        name: "Annual Dental Limit",
        amount: 5000,
        currency: "USD",
        period: "Annual",
        limitType: "independent",
        memberRoles: ["Employee", "Spouse", "Child"],
        serviceTypes: ["DT"],
        description: "Annual limit for dental services",
      },
      {
        id: "limit-006",
        name: "Orthodontic Lifetime Limit",
        amount: 15000,
        currency: "USD",
        period: "Lifetime",
        limitType: "independent",
        memberRoles: ["Child"],
        serviceTypes: ["DT"],
        description: "Lifetime limit for orthodontic treatment",
      },
    ],
    specialRules: {
      coPayments: [
        {
          id: "copay-004",
          type: "Percentage",
          serviceType: "DT",
          paymentMethod: "Per Visit",
          amount: 20,
          unit: "%",
          isSequential: false,
          description: "20% co-payment for dental services",
        },
      ],
      benefitCoordination: [
        {
          id: "bc-003",
          type: "Secondary",
          description: "This plan acts as secondary coverage for dental",
          priority: 2,
        },
      ],
      regulatoryCompliance: {
        essentialHealthBenefits: {
          enabled: false,
          categories: [],
          exemptions: ["Orthodontic treatment for adults"],
        },
        preventiveCareExemptions: {
          enabled: true,
          services: ["Dental Cleaning", "Fluoride Treatment"],
          copaymentWaived: true,
        },
        mentalHealthParity: {
          enabled: false,
          treatmentLimits: false,
          financialRequirements: false,
          quantitativeLimits: false,
        },
      },
    },
    coPayments: [
      {
        id: "copay-004",
        type: "Percentage",
        serviceType: "DT",
        paymentMethod: "Per Visit",
        amount: 20,
        unit: "%",
        isSequential: false,
        description: "20% co-payment for dental services",
      },
    ],
  },
  {
    id: "PL004",
    name: "Executive Health Package",
    type: "Corporate Self-Funded",
    status: "Active",
    createdDate: "2024-01-05",
    description: "Premium health package for executives with comprehensive coverage including alternative medicine",
    effectiveDate: "2024-01-01",
    expiryDate: "2024-12-31",
    serviceTypes: ["GP", "SP", "OC", "DT", "HP", "SG", "MT", "AM"],
    subServiceTypes: {
      GP: ["gp_primary_care", "gp_preventive", "gp_chronic", "gp_health_screening", "gp_wellness"],
      SP: ["sp_cardiology", "sp_dermatology", "sp_endocrinology", "sp_neurology", "sp_orthopedics", "sp_oncology"],
      OC: ["oc_examination", "oc_vision_correction", "oc_eye_surgery", "oc_low_vision"],
      DT: ["dt_preventive", "dt_restorative", "dt_oral_surgery", "dt_orthodontics"],
      HP: ["hp_room_board", "hp_nursing", "hp_hospital_services", "hp_emergency"],
      SG: ["sg_minor", "sg_major", "sg_specialized", "sg_reconstructive"],
      MT: ["mt_prenatal", "mt_delivery", "mt_postnatal", "mt_newborn"],
      AM: ["am_acupuncture", "am_chiropractic", "am_physiotherapy", "am_wellness"],
    },
    providerAccess: "select-access",
    selectedProviders: [
      {
        id: "prov-008",
        name: "Premium Medical Center",
        type: "Hospital",
        location: "Medical District",
        status: "Active",
        phone: "+1-555-0108",
        hours: "24/7",
      },
      {
        id: "prov-009",
        name: "Executive Health Clinic",
        type: "Clinic",
        location: "Business District",
        status: "Active",
        phone: "+1-555-0109",
        hours: "7AM-9PM",
      },
      {
        id: "prov-010",
        name: "Wellness Spa & Therapy",
        type: "Physiotherapy",
        location: "Wellness Center",
        status: "Active",
        phone: "+1-555-0110",
        hours: "6AM-10PM",
      },
      {
        id: "prov-011",
        name: "Maternity Care Center",
        type: "Hospital",
        location: "Women's Health District",
        status: "Active",
        phone: "+1-555-0111",
        hours: "24/7",
      },
    ],
    hasBillback: true,
    hasSpecialRules: true,
    limits: [
      {
        id: "limit-007",
        name: "Annual Medical Limit",
        amount: 200000,
        currency: "USD",
        period: "Annual",
        limitType: "independent",
        memberRoles: ["Employee", "Spouse"],
        serviceTypes: ["GP", "SP", "OC", "DT", "AM"],
        description: "Annual limit for outpatient medical services",
      },
      {
        id: "limit-008",
        name: "Hospitalization Limit",
        amount: 1000000,
        currency: "USD",
        period: "Annual",
        limitType: "independent",
        memberRoles: ["Employee", "Spouse"],
        serviceTypes: ["HP", "SG", "MT"],
        description: "Annual limit for hospitalization, surgery, and maternity",
      },
    ],
    specialRules: {
      coPayments: [
        {
          id: "copay-005",
          type: "Fixed Amount",
          serviceType: "GP",
          paymentMethod: "Per Visit",
          amount: 0,
          unit: "USD",
          isSequential: false,
          description: "No co-payment for GP consultations",
        },
        {
          id: "copay-006",
          type: "Percentage",
          serviceType: "SP",
          paymentMethod: "Per Visit",
          amount: 10,
          unit: "%",
          isSequential: false,
          description: "10% co-payment for specialist consultations",
        },
      ],
      benefitCoordination: [
        {
          id: "bc-004",
          type: "Primary",
          description: "This plan acts as primary coverage for all services",
          priority: 1,
        },
      ],
      regulatoryCompliance: {
        essentialHealthBenefits: {
          enabled: true,
          categories: ["Ambulatory", "Emergency", "Hospitalization", "Maternity", "Mental Health"],
          exemptions: [],
        },
        preventiveCareExemptions: {
          enabled: true,
          services: ["Annual Checkup", "Health Screening", "Executive Physical"],
          copaymentWaived: true,
        },
        mentalHealthParity: {
          enabled: true,
          treatmentLimits: false,
          financialRequirements: false,
          quantitativeLimits: false,
        },
      },
    },
    coPayments: [
      {
        id: "copay-005",
        type: "Fixed Amount",
        serviceType: "GP",
        paymentMethod: "Per Visit",
        amount: 0,
        unit: "USD",
        isSequential: false,
        description: "No co-payment for GP consultations",
      },
      {
        id: "copay-006",
        type: "Percentage",
        serviceType: "SP",
        paymentMethod: "Per Visit",
        amount: 10,
        unit: "%",
        isSequential: false,
        description: "10% co-payment for specialist consultations",
      },
    ],
  },
  {
    id: "PL005",
    name: "Maternity Care Plan",
    type: "GHS: Group Hospitalization & Surgery",
    status: "Inactive",
    createdDate: "2023-12-15",
    description: "Specialized maternity and newborn care coverage with comprehensive prenatal and postnatal benefits",
    effectiveDate: "2023-12-01",
    expiryDate: "2023-12-31",
    serviceTypes: ["GP", "SP", "MT", "HP"],
    subServiceTypes: {
      GP: ["gp_primary_care", "gp_preventive"],
      SP: ["sp_gynecology", "sp_pediatrics"],
      MT: ["mt_prenatal", "mt_delivery", "mt_postnatal", "mt_newborn", "mt_complications"],
      HP: ["hp_room_board", "hp_nursing", "hp_hospital_services"],
    },
    providerAccess: "panel",
    selectedProviders: [
      {
        id: "prov-012",
        name: "Women's Health Hospital",
        type: "Hospital",
        location: "Medical Center",
        status: "Active",
        phone: "+1-555-0112",
        hours: "24/7",
      },
      {
        id: "prov-013",
        name: "Prenatal Care Clinic",
        type: "Clinic",
        location: "Healthcare District",
        status: "Active",
        phone: "+1-555-0113",
        hours: "8AM-8PM",
      },
      {
        id: "prov-014",
        name: "Pediatric Care Center",
        type: "Clinic",
        location: "Children's Medical Plaza",
        status: "Active",
        phone: "+1-555-0114",
        hours: "7AM-7PM",
      },
    ],
    hasBillback: false,
    hasSpecialRules: true,
    limits: [
      {
        id: "limit-009",
        name: "Maternity Limit",
        amount: 25000,
        currency: "USD",
        period: "Per Pregnancy",
        limitType: "independent",
        memberRoles: ["Employee", "Spouse"],
        serviceTypes: ["MT", "HP"],
        description: "Limit per pregnancy for maternity and related hospitalization",
      },
      {
        id: "limit-010",
        name: "Newborn Care Limit",
        amount: 10000,
        currency: "USD",
        period: "Per Birth",
        limitType: "independent",
        memberRoles: ["Child"],
        serviceTypes: ["SP", "HP"],
        description: "Limit per birth for newborn care and complications",
      },
    ],
    specialRules: {
      coPayments: [
        {
          id: "copay-007",
          type: "Fixed Amount",
          serviceType: "MT",
          paymentMethod: "Per Visit",
          amount: 25,
          unit: "USD",
          isSequential: false,
          description: "Fixed co-payment for maternity visits",
        },
      ],
      benefitCoordination: [
        {
          id: "bc-005",
          type: "Primary",
          description: "This plan acts as primary coverage for maternity services",
          priority: 1,
        },
      ],
      regulatoryCompliance: {
        essentialHealthBenefits: {
          enabled: true,
          categories: ["Maternity", "Newborn Care"],
          exemptions: [],
        },
        preventiveCareExemptions: {
          enabled: true,
          services: ["Prenatal Checkups", "Newborn Screening"],
          copaymentWaived: true,
        },
        mentalHealthParity: {
          enabled: true,
          treatmentLimits: false,
          financialRequirements: false,
          quantitativeLimits: false,
        },
      },
    },
    coPayments: [
      {
        id: "copay-007",
        type: "Fixed Amount",
        serviceType: "MT",
        paymentMethod: "Per Visit",
        amount: 25,
        unit: "USD",
        isSequential: false,
        description: "Fixed co-payment for maternity visits",
      },
    ],
  },
]

// Function to initialize dummy plans if storage is empty
export function initializeDummyPlans(): void {
  if (PlanStorage.isEmpty()) {
    console.log("Initializing dummy plan data...")
    PlanStorage.savePlans(dummyPlans)
    console.log(`Initialized ${dummyPlans.length} dummy plans`)
  }
}

// Function to reset plans to dummy data (for testing)
export function resetToDefaultPlans(): void {
  console.log("Resetting to default plan data...")
  PlanStorage.savePlans(dummyPlans)
  console.log(`Reset to ${dummyPlans.length} default plans`)
}

// Export dummy plans for direct access
export { dummyPlans }
