import type { Provider } from "@/types/plan-creation-form"

export const DUMMY_PROVIDERS: Provider[] = [
  // Hospitals
  {
    id: "hosp-1",
    name: "Hospital Kuala Lumpur",
    address: "Jalan Pahang, 53000 Kuala Lumpur, Wilayah Persekutuan",
    phone: "+603-2615-5555",
    hours: "24/7",
    type: "Hospital",
  },
  {
    id: "hosp-2",
    name: "Gleneagles Hospital Kuala Lumpur",
    address: "286 & 288, Jalan Ampang, 50450 Kuala Lumpur",
    phone: "+603-4141-3000",
    hours: "24/7",
    type: "Hospital",
  },
  {
    id: "hosp-3",
    name: "Prince Court Medical Centre",
    address: "39, Jalan Kia Peng, 50450 Kuala Lumpur",
    phone: "+603-2160-0000",
    hours: "24/7",
    type: "Hospital",
  },
  {
    id: "hosp-4",
    name: "Pantai Hospital Kuala Lumpur",
    address: "8, Jalan Bukit Pantai, 59100 Kuala Lumpur",
    phone: "+603-2296-0888",
    hours: "24/7",
    type: "Hospital",
  },
  {
    id: "hosp-5",
    name: "Hospital Sultanah Aminah",
    address: "Jalan Persiaran Abu Bakar Sultan, 80100 Johor Bahru, Johor",
    phone: "+607-223-3333",
    hours: "24/7",
    type: "Hospital",
  },
  {
    id: "hosp-6",
    name: "Penang General Hospital",
    address: "Jalan Residensi, 10990 George Town, Pulau Pinang",
    phone: "+604-222-5333",
    hours: "24/7",
    type: "Hospital",
  },
  // GP Clinics
  {
    id: "gp-1",
    name: "Klinik Kesihatan Cheras",
    address: "Jalan Cheras, 56000 Kuala Lumpur",
    phone: "+603-9130-7033",
    hours: "8AM-5PM",
    type: "GP Clinic",
  },
  {
    id: "gp-2",
    name: "Poliklinik Setapak",
    address: "Jalan Genting Klang, 53300 Kuala Lumpur",
    phone: "+603-4142-4900",
    hours: "8AM-10PM",
    type: "GP Clinic",
  },
  {
    id: "gp-3",
    name: "Klinik Primer 1Malaysia Sg. Besi",
    address: "Jalan Sungai Besi, 57100 Kuala Lumpur",
    phone: "+603-7982-6495",
    hours: "8AM-5PM",
    type: "GP Clinic",
  },
  {
    id: "gp-4",
    name: "Klinik Desa Pandan",
    address: "Jalan Desa Pandan, 55100 Kuala Lumpur",
    phone: "+603-9221-1425",
    hours: "8AM-12PM, 2PM-5PM",
    type: "GP Clinic",
  },
  {
    id: "gp-5",
    name: "Klinik Kesihatan Petaling Jaya",
    address: "Jalan Yong Shook Lin, 46200 Petaling Jaya, Selangor",
    phone: "+603-7954-2935",
    hours: "8AM-5PM",
    type: "GP Clinic",
  },
  {
    id: "gp-6",
    name: "Klinik Pakar KPJ Seremban",
    address: "Lot 6219-6220, Jalan Toman 1, 70200 Seremban, Negeri Sembilan",
    phone: "+606-633-3999",
    hours: "9AM-6PM",
    type: "GP Clinic",
  },
  // Pharmacies
  {
    id: "pharm-1",
    name: "Guardian Pharmacy KLCC",
    address: "Suria KLCC, 50088 Kuala Lumpur",
    phone: "+603-2382-0706",
    hours: "10AM-10PM",
    type: "Pharmacy",
  },
  {
    id: "pharm-2",
    name: "Caring Pharmacy Bangsar Village",
    address: "Bangsar Village II, 59100 Kuala Lumpur",
    phone: "+603-2282-3301",
    hours: "10AM-10PM",
    type: "Pharmacy",
  },
  {
    id: "pharm-3",
    name: "Watsons Mid Valley",
    address: "Mid Valley Megamall, 58000 Kuala Lumpur",
    phone: "+603-2938-3800",
    hours: "10AM-10PM",
    type: "Pharmacy",
  },
  {
    id: "pharm-4",
    name: "Farmasi Kerajaan Hospital Kuala Lumpur",
    address: "Jalan Pahang, 53000 Kuala Lumpur",
    phone: "+603-2615-5555",
    hours: "8AM-5PM",
    type: "Pharmacy",
  },
  {
    id: "pharm-5",
    name: "Big Pharmacy Subang Jaya",
    address: "Empire Shopping Gallery, 47500 Subang Jaya, Selangor",
    phone: "+603-8024-2288",
    hours: "10AM-10PM",
    type: "Pharmacy",
  },
  {
    id: "pharm-6",
    name: "Alpro Pharmacy Penang",
    address: "Gurney Plaza, 10250 George Town, Pulau Pinang",
    phone: "+604-227-8899",
    hours: "10AM-10PM",
    type: "Pharmacy",
  },
  // Physiotherapy Centers
  {
    id: "physio-1",
    name: "Physiotherapy Department Hospital Kuala Lumpur",
    address: "Jalan Pahang, 53000 Kuala Lumpur",
    phone: "+603-2615-5555",
    hours: "8AM-5PM",
    type: "Physiotherapy Center",
  },
  {
    id: "physio-2",
    name: "Ace Physiotherapy & Sports Injury Centre",
    address: "Jalan 17/45, 46400 Petaling Jaya, Selangor",
    phone: "+603-7932-1234",
    hours: "9AM-7PM",
    type: "Physiotherapy Center",
  },
  {
    id: "physio-3",
    name: "PhysioActive Bangsar",
    address: "Jalan Maarof, 59000 Kuala Lumpur",
    phone: "+603-2094-5678",
    hours: "8AM-8PM",
    type: "Physiotherapy Center",
  },
  {
    id: "physio-4",
    name: "Rehab Physiotherapy Centre",
    address: "Jalan SS15/8B, 47500 Subang Jaya, Selangor",
    phone: "+603-5879-9012",
    hours: "9AM-6PM",
    type: "Physiotherapy Center",
  },
  {
    id: "physio-5",
    name: "Penang Physiotherapy & Rehab Centre",
    address: "Jalan Gottlieb, 10350 George Town, Pulau Pinang",
    phone: "+604-228-3456",
    hours: "8AM-6PM",
    type: "Physiotherapy Center",
  },
  {
    id: "physio-6",
    name: "Sports Medicine & Physiotherapy Johor",
    address: "Jalan Harmonium 23/2, 81200 Johor Bahru, Johor",
    phone: "+607-331-7890",
    hours: "9AM-7PM",
    type: "Physiotherapy Center",
  },
]
